name: hub

x-common-settings: &common-settings
  restart: always

services:
  apigw:
    <<: *common-settings
    build:
      context: nginx
      dockerfile: dockerfile
    container_name: apigw
    ports:
      - 80:80
    depends_on:
      #- microphoto
      - microuser
      #- microtagger
    networks:
      - frontend

  microuser:
    <<: *common-settings
    build:
      context: microUser
      dockerfile: dockerfile
    #container_name: microuser
    depends_on:
      - userdb
    deploy:
      replicas: 3
    networks:
      - frontend
      - backend

#  microphoto:
#    <<: *common-settings
#    build:
#      context: microPhoto
#      dockerfile: dockerfile
#    container_name: microphoto
#    depends_on:
#      - photodb
#    scale: 3
#    networks:
#      - frontend
#      - backend
#
#  microtagger:
#    <<: *common-settings
#    build:
#      context: .
#      dockerfile: microTagger/dockerfile
#    container_name: microtagger
#    scale: 3
#    networks:
#      - backend

  userdb:
    <<: *common-settings
    build:
      context: UserDatabaseDocker
      dockerfile: dockerfile
    container_name: userdb
    ports:
      - 9999:27017
    networks:
      - backend
    volumes:
      - user_data:/data/db

  photodb:
    <<: *common-settings
    build:
      context: PhotoDatabaseDocker
      dockerfile: dockerfile
    container_name: photodb
    ports:
      - 9998:27017
    networks:
      - backend
    volumes:
      - photo_data:/data/db

volumes:
  photo_data:
  user_data:

networks:
  backend:
  frontend:

