# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\nReplyToken\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x0cReplySuccess\x12\x0f\n\x07success\x18\x01 \x01(\t2j\n\x0bUserService\x12+\n\tUserLogin\x12\n.user.User\x1a\x10.user.ReplyToken\"\x00\x12.\n\nUserSignup\x12\n.user.User\x1a\x12.user.ReplySuccess\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=62
  _globals['_REPLYTOKEN']._serialized_start=64
  _globals['_REPLYTOKEN']._serialized_end=91
  _globals['_REPLYSUCCESS']._serialized_start=93
  _globals['_REPLYSUCCESS']._serialized_end=124
  _globals['_USERSERVICE']._serialized_start=126
  _globals['_USERSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
