FROM python:3.11
WORKDIR /usr/src/app
COPY . .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install Flask --upgrade
CMD ["flask","--app", "microPhoto", "run", "--host=0.0.0.0"]