global:
  scrape_interval:  15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: microuser
    static_configs:
      - targets: ['hub-microuser-1:9000']

  - job_name: microphoto
    static_configs:
      - targets: ['hub-microphoto-1:9000']

  - job_name: microtagger
    static_configs:
      - targets: [ 'hub-microtagger-1:9000' ]
