apiVersion: v1
kind: Service
metadata:
  name: microuser-service
  namespace: dsbd
spec:
  selector:
    app: microuser
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: pod
    - name: exporter
      port: 9000
      targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microuser-deploy
  namespace: dsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microuser
  template:
    metadata:
      labels:
        app: microuser
    spec:
      containers:
        - name: microuser-container
          image: al3gr/microuser:1.0
          ports:
            - containerPort: 5000
            - containerPort: 9000
          env:
            - name: token_secret
              value: metro
            - name: mongo_connection
              value: mongodb://userdb:27017/
            - name: mongo_user
              value: DS
            - name: mongo_pwd
              value: "2023"
          command: ["flask", "--app", "microUser", "run", "--host=0.0.0.0"]

